<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3schedule\models\base;

use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "schedule_schedule".
 *
 * @property integer $id
 * @property integer $subscriber_id
 * @property string $month_day
 * @property string $week_day
 * @property string $hour
 * @property string $minute
 *
 * @property \d3yii2\d3schedule\models\scheduleSubscriber $subscriber
 * @property string $aliasModel
 */
abstract class ScheduleSchedule extends ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'schedule_schedule';
    }


    /**
     * @inheritdoc
     */
    public function rules(): array
    {
        return [
            [['subscriber_id'], 'required'],
            [['subscriber_id'], 'integer'],
            [['month_day', 'week_day', 'hour', 'minute'], 'string', 'max' => 255],
            [['subscriber_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3schedule\models\ScheduleSubscriber::class, 'targetAttribute' => ['subscriber_id' => 'id']],
            [['id','subscriber_id'],'integer' ,'min' => 0 ,'max' => 65535]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3schedule', 'ID'),
            'subscriber_id' => Yii::t('d3schedule', 'Subscriber'),
            'month_day' => Yii::t('d3schedule', 'Month days'),
            'week_day' => Yii::t('d3schedule', 'Week days'),
            'hour' => Yii::t('d3schedule', 'Hours'),
            'minute' => Yii::t('d3schedule', 'Minutes'),
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getSubscriber()
    {
        return $this->hasOne(\d3yii2\d3schedule\models\ScheduleSubscriber::class, ['id' => 'subscriber_id']);
    }


}
