<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3schedule\models\base;

use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\Exception;

/**
 * This is the base-model class for table "schedule_subscriber_type".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \d3yii2\d3schedule\models\scheduleSubscriber[] $scheduleSubscribers
 * @property string $aliasModel
 */
abstract class ScheduleSubscryberType extends ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'schedule_subscriber_type';
    }


    /**
     * @inheritdoc
     */
    public function rules(): array
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 50],
            [['id'],'integer' ,'min' => 0 ,'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3schedule', 'ID'),
            'name' => Yii::t('d3schedule', 'Name'),
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getscheduleSubscribers()
    {
        return $this->hasMany(\d3yii2\d3schedule\models\ScheduleSubscriber::class, ['type_id' => 'id']);
    }

    /**
     * @return \d3yii2\d3schedule\models\scheduleSubscriber
     * @throws Exception
     */
    public function newscheduleSubscribers()
    {
        if ($this->getIsNewRecord()){
            throw new Exception('Can not create new related record for new record!');
        }
        $model = new \d3yii2\d3schedule\models\ScheduleSubscriber();
        $model->type_id = $this->id;
        return $model;
    }



}
